repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.9 
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
      
  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: ty check . --ignore unresolved-import
        language: python

      - id: pytest
        name: Run tests
        entry: uv run --extra test pytest
        language: system
        pass_filenames: false
        always_run: true
        args: ["-v", "--tb=short"]