name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

jobs:
  build_and_test:
    name: Build, Lint, and Type Check Python Environment with uv
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:python3.12-bookworm-slim

    steps:
      - uses: actions/checkout@v4

      - name: Lint with Ruff
        run: |
          uv run ruff check .

      - name: Check formatting with Ruff
        run: |
          uv run ruff format --check .

      - name: Type check with mypy
        run: |
          uv run mypy .