name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint with ruff and mypy
    runs-on: ghcr.io/astral-sh/uv:python3.12-bookworm-slim
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Export uv path
      run: |
        echo "PATH=/opt/uv/bin:$PATH" >> $GITHUB_ENV
    
    - name: Lint with ruff
      run: |
        uv pip install ruff
        ruff check .
        ruff format --check .
    
    - name: Type check with mypy
      run: |
        uv pip install mypy pandas-stubs types-seaborn
        mypy .