name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

jobs:
  lint:
    name: Ruff lint and format
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:python3.12-bookworm-slim

    steps:
      - uses: actions/checkout@v4

      - name: Install project and dependencies
        run: |
          uv pip install --system ruff

      - name: Lint with Ruff
        run: |
          ruff check .

      - name: Check formatting with Ruff
        run: |
          ruff format --check .

  typecheck:
    name: Type check with mypy
    needs: lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:python3.12-bookworm-slim

    steps:
      - uses: actions/checkout@v4

      - name: Install project and dependencies
        run: |
          uv pip install --system mypy

      - name: Run mypy
        run: |
          mypy .