name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

jobs:
  setup_python_environment:
    name: Setup Python Environment with uv
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:python3.12-bookworm-slim

    steps:
      - uses: actions/checkout@v4
      - name: Create uv venv and install dependencies
        run: |
          uv venv

  lint:
    name: Ruff lint and format
    needs: setup_python_environment
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:python3.12-bookworm-slim

    steps:
      - uses: actions/checkout@v4
      - name: Lint with Ruff
        run: |
          uv run ruff check .

      - name: Check formatting with Ruff
        run: |
          uv run ruff format --check .

  typecheck:
    name: Type check with mypy
    needs: setup_python_environment 
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:python3.12-bookworm-slim

    steps:
      - uses: actions/checkout@v4
      - name: Run mypy
        run: |
          uv run mypy .