name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

jobs:
  lint:
    name: Lint with ruff and mypy
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:python3.12-bookworm-slim
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install project and dependencies
      run: |
        uv venv
    
    - name: Lint with ruff
      run: |
        uv run ruff check .
    
    - name: Type check with mypy
      run: |
        uv run mypy .
  